/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frog;

import java.awt.Dimension;
import java.awt.event.KeyEvent;

/**
 *
 * @author chuky
 */
public class FrogGame extends javax.swing.JFrame {

    /**
     * Creates new form FrogGame
     */
    Dimension tam;
    PanelFrog fg;
    boolean pause = false;

    public FrogGame() {
        this.setTitle("The Frog's Game");
        initComponents();
        tam = this.getSize();
        fg = new PanelFrog(tam.width, tam.height);
        this.add(fg);
        fg.setVisible(true);
        setLocationRelativeTo(null); //Centrado
        fg.sonidoR.loop();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_RIGHT || evt.getKeyCode() == KeyEvent.VK_D && !fg.izq) {
            fg.der = true;
            fg.izq = false;
            fg.arr = false;
            fg.aba = false;
        } else if (evt.getKeyCode() == KeyEvent.VK_LEFT || evt.getKeyCode() == KeyEvent.VK_A && !fg.der) {
            fg.der = false;
            fg.izq = true;
            fg.arr = false;
            fg.aba = false;
        } else if (evt.getKeyCode() == KeyEvent.VK_UP || evt.getKeyCode() == KeyEvent.VK_W && !fg.aba) {
            fg.der = false;
            fg.izq = false;
            fg.arr = true;
            fg.aba = false;
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN || evt.getKeyCode() == KeyEvent.VK_S && !fg.arr) {
            fg.der = false;
            fg.izq = false;
            fg.arr = false;
            fg.aba = true;
        } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            if (!pause) {
                fg.sonidoR.stop();
                fg.tiempo.suspend();
                fg.Rana.suspend();
                fg.Auto1.suspend();
                fg.Auto2.suspend();
                fg.Auto3.suspend();
                fg.Auto4.suspend();
                fg.Auto5.suspend();
                fg.Auto6.suspend();
                fg.Auto7.suspend();
                fg.Auto8.suspend();
                fg.Auto9.suspend();
                fg.Wood1.suspend();
                fg.Wood2.suspend();
                fg.Wood3.suspend();
                fg.Fish1.suspend();
                fg.Fish2.suspend();
                fg.Wood4.suspend();
                fg.Wood5.suspend();
                fg.Wood6.suspend();
                pause = true;
            } else {
                fg.sonidoR.loop();
                fg.tiempo.resume();
                fg.Rana.resume();
                fg.Auto1.resume();
                fg.Auto2.resume();
                fg.Auto3.resume();
                fg.Auto4.resume();
                fg.Auto5.resume();
                fg.Auto6.resume();
                fg.Auto7.resume();
                fg.Auto8.resume();
                fg.Auto9.resume();
                fg.Wood1.resume();
                fg.Wood2.resume();
                fg.Wood3.resume();
                fg.Fish1.resume();
                fg.Fish2.resume();
                fg.Wood4.resume();
                fg.Wood5.resume();
                fg.Wood6.resume();
                pause = false;
            }
        }
    }//GEN-LAST:event_formKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrogGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrogGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrogGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrogGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new FrogGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
